layout_spectrum: 0.2071339
favicon: null
name: 'Grand Rapids Bars '
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.3302601666655391
  lightness: 0.4987484
  saturation: 0.491239
  rhythmicContrast: 0.5012516
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.1295369
