name: 'Grand Rapids Bars '
favicon: null
layout_spectrum: 0.3409732503350824
typography_spectrum: 0.9916415957268327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.33026016666553915
  lightness: 0.6076926162932068
  saturation: 0.58423818834126
  rhythmicContrast: 0.8073193354066461
purpose: []
